### ISSUE TITLE
Error: Your SDK doesn't have dart2aot or dart2native

### ISSUE THREAD

**Issue by filiph** [google/dart_cli_pkg#101]
Hi,

I'm getting an error that I didn't get before in GitHub Actions:

```
pkg-compile-native
  failed: Your SDK doesn't have dart2aot or dart2native. This probably means that you're using a 32-bit SDK, which doesn't support native compilation.

GrinderException: Your SDK doesn't have dart2aot or dart2native. This probably means that you're using a 32-bit SDK, which doesn't support native compilation.
#0      GrinderContext.fail (package:grinder/src/grinder_context.dart:42:5)
#1      fail (package:grinder/src/grinder_context.dart:59:39)
#2      _compileNative (package:cli_pkg/src/standalone.dart:81:5)
#3      _rootRun (dart:async/zone.dart:14[26](https://github.com/filiph/linkcheck/runs/6373828609?check_suite_focus=true#step:8:26):13)
...
Error: Process completed with exit code 1.
```

Whole run [here.](https://github.com/filiph/linkcheck/runs/6373828609?check_suite_focus=true)

Is this because `dart2aot` and `dart2native` do not exist anymore? Or has something changed with the default Dart binaries that prevents `cli_pkg` to do its work inside GitHub Actions?

Here is the setup, which I'm told is very standard:

- GitHub actions workflow: https://github.com/filiph/linkcheck/blob/master/.github/workflows/release.yml
- grind.dart: https://github.com/filiph/linkcheck/blob/master/tool/grind.dart

**Comment by nex3** [comment]
What version of `cli_pkg` are you using? This check was removed in #88.

**Comment by filiph** [comment]
Oh! I'm sorry, I was using `1.4.0`. 🤦  I forgot to check that because, originally, I thought the problem was with `grinder` (which was at the most recent). Anyway, don't mind me please. Nothing to see here.
