### ISSUE TITLE
Relative symbolic links to generated shell scripts fail to execute on linux

### ISSUE THREAD

**Issue by RayDeCampo** [google/dart_cli_pkg#43]
Apparent the dart-sass project uses this project to create the executables.  When I created a relative symbolic link to the dart-sass shell script it failed to execute on linux because `readlink` does not return the full path.  In this case `readlink -f` is needed, however I see that it is not used because of an issue on OS X.

Please see https://github.com/sass/dart-sass/issues/978 for more details.

**Comment by nex3** [comment]
I'm folding this into #67, since once we're generating native executables on Linux we won't need to have a wrapper script at all.
