### ISSUE TITLE
The generated github release note look weird for some kind of links

### ISSUE THREAD

**Issue by stof** [google/dart_cli_pkg#65]
see https://github.com/sass/dart-sass/releases/tag/1.28.0 for an example:
![image](https://user-images.githubusercontent.com/439401/98003566-28925500-1def-11eb-97b7-1fa4fe8b18ba.png)

**Comment by nex3** [comment]
Looks like we're treating Markdown link reference blocks as though they're paragraphs and performing newline folding on them.
