### ISSUE TITLE
GitHub changelog removes line breaks before list items

### ISSUE THREAD

**Issue by leoafarias** [google/dart_cli_pkg#78]
When running the command, everything works well, but the `Changelog.md` section for the version is displayed without the line breaks.

Please view the following link:
https://github.com/leoafarias/fvm/releases/tag/2.0.0

When digging into the code, it seems that this was done by design. (or maybe I am missing something)
https://github.com/google/dart_cli_pkg/blob/master/lib/src/github.dart#L190

Before making any changes to this, I wanted to make sure this change can be done so it's formatted correctly.

**Comment by nex3** [comment]
GitHub actually has subtly different Markdown parsing that it uses for rendering Markdown files and for release notes. In files, newlines within paragraphs are ignored, but in release notes (as well as issues, comments, and a number of other places) newlines within paragraphs are converted to user-visible line breaks. To ensure that the CHANGELOG file's formatting is preserved, we convert newlines to spaces before passing it as release notes.

That said, we shouldn't strip newlines if they're before lists. Do you want to take a crack at fixing the issue?

**Comment by leoafarias** [comment]
@nex3 just before jumping in on this, I was looking through the sass release notes, and seems the problem does not happen there. My markdown linter seems to replace `*` for `-` do you think the issue has to do with the list character?

**Comment by nex3** [comment]
No, I think the difference is that we include full blank lines between each bullet point.
