### ISSUE TITLE
Add an easy way to configure Travis credentials

### ISSUE THREAD

**Issue by nex3** [google/dart_cli_pkg#8]
All deployments require credentials, and making those credentials available to the deploy steps can be error-prone and annoying. We should provide a way to do this configuration on the user's behalf.

One possibility would be to provide our own `pub run`-based CLI which would authenticate with the various services and write the result to the user's `.travis.yml`.

**Comment by stof** [comment]
@nex3 with the migration from travis to GA for sass (and maybe also other tools using that package as Travis dropped their free plan for open-source), I think this should be closed. On GA, secrets cannot be stored in the config file in an encrypted way.

**Comment by nex3** [comment]
Agreed.
